# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Roxy_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Roxy(object):
    def setupUi(self, Roxy):
        Roxy.setObjectName("Roxy")
        Roxy.resize(839, 638)
        self.Screen = QtWidgets.QWidget(Roxy)
        self.Screen.setGeometry(QtCore.QRect(-1, -1, 841, 641))
        self.Screen.setStyleSheet("background-image: url(:/newPrefix/D:/Virtual_Assisstance_Project/Personal Voice "
                                  "Assistant.gif);")
        self.Screen.setObjectName("Screen")
        self.Start_Button = QtWidgets.QPushButton(self.Screen)
        self.Start_Button.setGeometry(QtCore.QRect(30, 480, 191, 91))
        self.Start_Button.setObjectName("Start_Button")

        self.retranslateUi(Roxy)
        QtCore.QMetaObject.connectSlotsByName(Roxy)

    def retranslateUi(self, Roxy):
        _translate = QtCore.QCoreApplication.translate
        Roxy.setWindowTitle(_translate("Roxy", "Dialog"))
        self.Start_Button.setText(_translate("Roxy", "Start"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Roxy = QtWidgets.QDialog()
    ui = Ui_Roxy()
    ui.setupUi(Roxy)
    Roxy.show()
    sys.exit(app.exec_())
