# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Roxy_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Roxy(object):
    def setupUi(self, Roxy):
        Roxy.setObjectName("Roxy")
        Roxy.resize(1017, 745)
        self.Quit_Button = QtWidgets.QPushButton(Roxy)
        self.Quit_Button.setGeometry(QtCore.QRect(840, 370, 141, 71))
        self.Quit_Button.setStyleSheet("color: rgb(255, 0, 0);\n"
                                       "text-decoration: underline;\n"
                                       "font: 14pt \"MS Shell Dlg 2\";")
        self.Quit_Button.setObjectName("Quit_Button")
        self.Start_Button = QtWidgets.QPushButton(Roxy)
        self.Start_Button.setGeometry(QtCore.QRect(840, 260, 141, 71))
        self.Start_Button.setStyleSheet("color: rgb(255, 0, 0);\n"
                                        "text-decoration: underline;\n"
                                        "font: 14pt \"MS Shell Dlg 2\";")
        self.Start_Button.setObjectName("Start_Button")
        self.label = QtWidgets.QLabel(Roxy)
        self.label.setGeometry(QtCore.QRect(0, 0, 811, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/ASUS/Pictures/female-virtual-assistant-icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Roxy)
        QtCore.QMetaObject.connectSlotsByName(Roxy)

    def retranslateUi(self, Roxy):
        _translate = QtCore.QCoreApplication.translate
        Roxy.setWindowTitle(_translate("Roxy", "Roxy"))
        self.Quit_Button.setText(_translate("Roxy", "Quit"))
        self.Start_Button.setText(_translate("Roxy", "Start"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Roxy = QtWidgets.QDialog()
    ui = Ui_Roxy()
    ui.setupUi(Roxy)
    Roxy.show()
    sys.exit(app.exec_())
