# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Roxy_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Roxy(object):
    def setupUi(self, Roxy):
        Roxy.setObjectName("Roxy")
        Roxy.resize(839, 638)
        self.frame = QtWidgets.QFrame(Roxy)
        self.frame.setGeometry(QtCore.QRect(0, 0, 841, 641))
        self.frame.setStyleSheet("background-image: url(:/newPrefix/D:/Virtual_Assisstance_Project/Personal Voice Assistant.gif);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 480, 181, 91))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Roxy)
        QtCore.QMetaObject.connectSlotsByName(Roxy)

    def retranslateUi(self, Roxy):
        _translate = QtCore.QCoreApplication.translate
        Roxy.setWindowTitle(_translate("Roxy", "Dialog"))
        self.pushButton.setText(_translate("Roxy", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Roxy = QtWidgets.QDialog()
    ui = Ui_Roxy()
    ui.setupUi(Roxy)
    Roxy.show()
    sys.exit(app.exec_())
